version: '3.9'
services:
  discovery-server:
    image: discovery-server:latest
    build: ./discovery-server
    ports:
      - "8761:8761"

  kitchen-service:
    image: kitchen-service:latest
    build: ./kitchen
    depends_on:
      - discovery-server
    ports:
      - "8081:8081"
    environment:
      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=8761
      - DB_URL=${DB_URL:-jdbc:postgresql://postgresql:5432/postgres}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      
  tracker-service:
    image: tracker-service:latest
    build: ./tracker
    depends_on:
      - discovery-server
    ports:
      - "8082:8082"
    environment:
      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=8761
      - DB_URL=${DB_URL:-jdbc:postgresql://postgresql:5432/postgres}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_CONN_INIT_SQL=${DB_CONN_INIT_SQL:-}
    
  api-gateway:
    image: api-gateway:latest
    build: ./api-gateway
    depends_on:
      - discovery-server
    ports:
      - "8080:8080"
    environment:
      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=8761  

networks:
  default:
    external:
      name: pizza-network